apiVersion: v1
kind: Service
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
spec:
  clusterIP: None
  selector:
    app: clickhouse-keeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: raft
      port: 9444
      targetPort: 9444

